[package]
name = "madfilter"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
base64 = "0.22.1"
clap = { version = "4.5.54", features = ["derive"] }
configparser = "3.1.0"
ini = "1.3.0"
mail-parser = "0.11.1"
tokio = { version = "1.49.0", features = ["full"] }
